import Foundation
import Observation
import ServiceManagement

// Generated by scripts/gen-preferences.py. Edit the table in that script, then run it.

/// User settings. Every property writes through to `UserDefaults` and posts `changedNotification`.
@MainActor
@Observable
final class Preferences {
    static let shared = Preferences()
    static let changedNotification = Notification.Name("IsletPreferencesChanged")
    private let defaults = UserDefaults.standard

    // MARK: General
    var hideInFullscreen: Bool { didSet { store(hideInFullscreen, "hideInFullscreen") } }
    var hideFromScreenCapture: Bool { didSet { store(hideFromScreenCapture, "hideFromScreenCapture") } }
    var simulatedNotch: Bool { didSet { store(simulatedNotch, "simulatedNotch") } }
    var displayTarget: String { didSet { store(displayTarget, "displayTarget") } }
    var notchHeightOffset: Double { didSet { store(notchHeightOffset, "notchHeightOffset") } }
    var notchWidthOffset: Double { didSet { store(notchWidthOffset, "notchWidthOffset") } }
    var contrastOutline: Bool { didSet { store(contrastOutline, "contrastOutline") } }
    var progressiveBlur: Bool { didSet { store(progressiveBlur, "progressiveBlur") } }
    var hapticFeedback: Bool { didSet { store(hapticFeedback, "hapticFeedback") } }
    var expandOnHover: Bool { didSet { store(expandOnHover, "expandOnHover") } }
    var hoverDelay: Double { didSet { store(hoverDelay, "hoverDelay") } }
    var gesturesEnabled: Bool { didSet { store(gesturesEnabled, "gesturesEnabled") } }
    var globalHotkey: Bool { didSet { store(globalHotkey, "globalHotkey") } }
    var animationSpeed: String { didSet { store(animationSpeed, "animationSpeed") } }
    // MARK: Battery
    var batteryEnabled: Bool { didSet { store(batteryEnabled, "batteryEnabled") } }
    var batteryDuration: Double { didSet { store(batteryDuration, "batteryDuration") } }
    var batteryLowPowerMode: Bool { didSet { store(batteryLowPowerMode, "batteryLowPowerMode") } }
    var batteryWarnLow: Bool { didSet { store(batteryWarnLow, "batteryWarnLow") } }
    var batteryLowThreshold: Int { didSet { store(batteryLowThreshold, "batteryLowThreshold") } }
    var batterySound: Bool { didSet { store(batterySound, "batterySound") } }
    var batteryHideLabel: Bool { didSet { store(batteryHideLabel, "batteryHideLabel") } }
    var batteryHidePercentage: Bool { didSet { store(batteryHidePercentage, "batteryHidePercentage") } }
    // MARK: Connectivity
    var connectivityEnabled: Bool { didSet { store(connectivityEnabled, "connectivityEnabled") } }
    var connectivityDuration: Double { didSet { store(connectivityDuration, "connectivityDuration") } }
    var connectivityWarnLow: Bool { didSet { store(connectivityWarnLow, "connectivityWarnLow") } }
    var connectivityLowThreshold: Int { didSet { store(connectivityLowThreshold, "connectivityLowThreshold") } }
    var connectivitySound: Bool { didSet { store(connectivitySound, "connectivitySound") } }
    // MARK: Focus
    var focusEnabled: Bool { didSet { store(focusEnabled, "focusEnabled") } }
    var focusDuration: Double { didSet { store(focusDuration, "focusDuration") } }
    var focusSound: Bool { didSet { store(focusSound, "focusSound") } }
    var focusHideLabel: Bool { didSet { store(focusHideLabel, "focusHideLabel") } }
    // MARK: Display HUD
    var displayHUDEnabled: Bool { didSet { store(displayHUDEnabled, "displayHUDEnabled") } }
    var displayHUDDuration: Double { didSet { store(displayHUDDuration, "displayHUDDuration") } }
    var displayHUDStyle: String { didSet { store(displayHUDStyle, "displayHUDStyle") } }
    var displayHUDPercentage: Bool { didSet { store(displayHUDPercentage, "displayHUDPercentage") } }
    var displayHUDHideLabel: Bool { didSet { store(displayHUDHideLabel, "displayHUDHideLabel") } }
    var keyboardHUDEnabled: Bool { didSet { store(keyboardHUDEnabled, "keyboardHUDEnabled") } }
    // MARK: Sound HUD
    var soundHUDEnabled: Bool { didSet { store(soundHUDEnabled, "soundHUDEnabled") } }
    var soundHUDDuration: Double { didSet { store(soundHUDDuration, "soundHUDDuration") } }
    var soundHUDStyle: String { didSet { store(soundHUDStyle, "soundHUDStyle") } }
    var soundHUDPercentage: Bool { didSet { store(soundHUDPercentage, "soundHUDPercentage") } }
    var soundHUDHideLabel: Bool { didSet { store(soundHUDHideLabel, "soundHUDHideLabel") } }
    var soundHUDShowDevice: Bool { didSet { store(soundHUDShowDevice, "soundHUDShowDevice") } }
    var replaceSystemHUD: Bool { didSet { store(replaceSystemHUD, "replaceSystemHUD") } }
    // MARK: Now Playing
    var nowPlayingEnabled: Bool { didSet { store(nowPlayingEnabled, "nowPlayingEnabled") } }
    var nowPlayingIdleDuration: Double { didSet { store(nowPlayingIdleDuration, "nowPlayingIdleDuration") } }
    var nowPlayingSneakPeek: Bool { didSet { store(nowPlayingSneakPeek, "nowPlayingSneakPeek") } }
    var waveformStyle: String { didSet { store(waveformStyle, "waveformStyle") } }
    var liveWaveform: Bool { didSet { store(liveWaveform, "liveWaveform") } }
    var compactWaveform: Bool { didSet { store(compactWaveform, "compactWaveform") } }
    var artworkFlip: Bool { didSet { store(artworkFlip, "artworkFlip") } }
    var siteIcons: Bool { didSet { store(siteIcons, "siteIcons") } }
    var hideWhileSourceActive: Bool { didSet { store(hideWhileSourceActive, "hideWhileSourceActive") } }
    var hideTitleExtras: Bool { didSet { store(hideTitleExtras, "hideTitleExtras") } }
    var actionShuffle: Bool { didSet { store(actionShuffle, "actionShuffle") } }
    var actionRepeat: Bool { didSet { store(actionRepeat, "actionRepeat") } }
    var actionCopy: Bool { didSet { store(actionCopy, "actionCopy") } }
    // MARK: Calendar
    var calendarEnabled: Bool { didSet { store(calendarEnabled, "calendarEnabled") } }
    var calendarReminderMinutes: Int { didSet { store(calendarReminderMinutes, "calendarReminderMinutes") } }
    var calendarSound: Bool { didSet { store(calendarSound, "calendarSound") } }
    var hourlyChime: Bool { didSet { store(hourlyChime, "hourlyChime") } }
    var calendarUseColor: Bool { didSet { store(calendarUseColor, "calendarUseColor") } }
    var calendarExcluded: [String] { didSet { store(calendarExcluded, "calendarExcluded") } }
    // MARK: Shelf
    var shelfEnabled: Bool { didSet { store(shelfEnabled, "shelfEnabled") } }
    // MARK: Lock screen
    var lockSoundOnLock: Bool { didSet { store(lockSoundOnLock, "lockSoundOnLock") } }
    var lockSoundOnUnlock: Bool { didSet { store(lockSoundOnUnlock, "lockSoundOnUnlock") } }
    // MARK: Extras
    var downloadsActivity: Bool { didSet { store(downloadsActivity, "downloadsActivity") } }
    var capsLockActivity: Bool { didSet { store(capsLockActivity, "capsLockActivity") } }
    var hasCompletedOnboarding: Bool { didSet { store(hasCompletedOnboarding, "hasCompletedOnboarding") } }

    /// Launch at login is owned by the system, not by UserDefaults.
    var launchAtLogin: Bool {
        get { SMAppService.mainApp.status == .enabled }
        set {
            do {
                if newValue { try SMAppService.mainApp.register() } else { try SMAppService.mainApp.unregister() }
            } catch {
                NSLog("Islet: launch at login failed: \(error)")
            }
        }
    }

    private static let defaultValues: [String: Any] = [
        "hideInFullscreen": true,
        "hideFromScreenCapture": false,
        "simulatedNotch": false,
        "displayTarget": "auto",
        "notchHeightOffset": 1.0,
        "notchWidthOffset": 0.0,
        "contrastOutline": false,
        "progressiveBlur": true,
        "hapticFeedback": true,
        "expandOnHover": true,
        "hoverDelay": 0.12,
        "gesturesEnabled": true,
        "globalHotkey": true,
        "animationSpeed": "fast",
        "batteryEnabled": true,
        "batteryDuration": 3.0,
        "batteryLowPowerMode": true,
        "batteryWarnLow": true,
        "batteryLowThreshold": 20,
        "batterySound": true,
        "batteryHideLabel": false,
        "batteryHidePercentage": false,
        "connectivityEnabled": true,
        "connectivityDuration": 3.0,
        "connectivityWarnLow": true,
        "connectivityLowThreshold": 20,
        "connectivitySound": false,
        "focusEnabled": true,
        "focusDuration": 3.0,
        "focusSound": false,
        "focusHideLabel": false,
        "displayHUDEnabled": true,
        "displayHUDDuration": 1.5,
        "displayHUDStyle": "glow",
        "displayHUDPercentage": true,
        "displayHUDHideLabel": false,
        "keyboardHUDEnabled": true,
        "soundHUDEnabled": true,
        "soundHUDDuration": 1.5,
        "soundHUDStyle": "accent",
        "soundHUDPercentage": true,
        "soundHUDHideLabel": false,
        "soundHUDShowDevice": true,
        "replaceSystemHUD": false,
        "nowPlayingEnabled": true,
        "nowPlayingIdleDuration": 3.0,
        "nowPlayingSneakPeek": true,
        "waveformStyle": "colored",
        "liveWaveform": false,
        "compactWaveform": true,
        "artworkFlip": true,
        "siteIcons": true,
        "hideWhileSourceActive": false,
        "hideTitleExtras": false,
        "actionShuffle": true,
        "actionRepeat": true,
        "actionCopy": true,
        "calendarEnabled": true,
        "calendarReminderMinutes": 15,
        "calendarSound": true,
        "hourlyChime": false,
        "calendarUseColor": true,
        "calendarExcluded": [],
        "shelfEnabled": true,
        "lockSoundOnLock": false,
        "lockSoundOnUnlock": true,
        "downloadsActivity": true,
        "capsLockActivity": true,
        "hasCompletedOnboarding": false,
    ]

    private init() {
        defaults.register(defaults: Self.defaultValues)
        hideInFullscreen = defaults.bool(forKey: "hideInFullscreen")
        hideFromScreenCapture = defaults.bool(forKey: "hideFromScreenCapture")
        simulatedNotch = defaults.bool(forKey: "simulatedNotch")
        displayTarget = defaults.string(forKey: "displayTarget") ?? "auto"
        notchHeightOffset = defaults.double(forKey: "notchHeightOffset")
        notchWidthOffset = defaults.double(forKey: "notchWidthOffset")
        contrastOutline = defaults.bool(forKey: "contrastOutline")
        progressiveBlur = defaults.bool(forKey: "progressiveBlur")
        hapticFeedback = defaults.bool(forKey: "hapticFeedback")
        expandOnHover = defaults.bool(forKey: "expandOnHover")
        hoverDelay = defaults.double(forKey: "hoverDelay")
        gesturesEnabled = defaults.bool(forKey: "gesturesEnabled")
        globalHotkey = defaults.bool(forKey: "globalHotkey")
        animationSpeed = defaults.string(forKey: "animationSpeed") ?? "fast"
        batteryEnabled = defaults.bool(forKey: "batteryEnabled")
        batteryDuration = defaults.double(forKey: "batteryDuration")
        batteryLowPowerMode = defaults.bool(forKey: "batteryLowPowerMode")
        batteryWarnLow = defaults.bool(forKey: "batteryWarnLow")
        batteryLowThreshold = defaults.integer(forKey: "batteryLowThreshold")
        batterySound = defaults.bool(forKey: "batterySound")
        batteryHideLabel = defaults.bool(forKey: "batteryHideLabel")
        batteryHidePercentage = defaults.bool(forKey: "batteryHidePercentage")
        connectivityEnabled = defaults.bool(forKey: "connectivityEnabled")
        connectivityDuration = defaults.double(forKey: "connectivityDuration")
        connectivityWarnLow = defaults.bool(forKey: "connectivityWarnLow")
        connectivityLowThreshold = defaults.integer(forKey: "connectivityLowThreshold")
        connectivitySound = defaults.bool(forKey: "connectivitySound")
        focusEnabled = defaults.bool(forKey: "focusEnabled")
        focusDuration = defaults.double(forKey: "focusDuration")
        focusSound = defaults.bool(forKey: "focusSound")
        focusHideLabel = defaults.bool(forKey: "focusHideLabel")
        displayHUDEnabled = defaults.bool(forKey: "displayHUDEnabled")
        displayHUDDuration = defaults.double(forKey: "displayHUDDuration")
        displayHUDStyle = defaults.string(forKey: "displayHUDStyle") ?? "glow"
        displayHUDPercentage = defaults.bool(forKey: "displayHUDPercentage")
        displayHUDHideLabel = defaults.bool(forKey: "displayHUDHideLabel")
        keyboardHUDEnabled = defaults.bool(forKey: "keyboardHUDEnabled")
        soundHUDEnabled = defaults.bool(forKey: "soundHUDEnabled")
        soundHUDDuration = defaults.double(forKey: "soundHUDDuration")
        soundHUDStyle = defaults.string(forKey: "soundHUDStyle") ?? "accent"
        soundHUDPercentage = defaults.bool(forKey: "soundHUDPercentage")
        soundHUDHideLabel = defaults.bool(forKey: "soundHUDHideLabel")
        soundHUDShowDevice = defaults.bool(forKey: "soundHUDShowDevice")
        replaceSystemHUD = defaults.bool(forKey: "replaceSystemHUD")
        nowPlayingEnabled = defaults.bool(forKey: "nowPlayingEnabled")
        nowPlayingIdleDuration = defaults.double(forKey: "nowPlayingIdleDuration")
        nowPlayingSneakPeek = defaults.bool(forKey: "nowPlayingSneakPeek")
        waveformStyle = defaults.string(forKey: "waveformStyle") ?? "colored"
        liveWaveform = defaults.bool(forKey: "liveWaveform")
        compactWaveform = defaults.bool(forKey: "compactWaveform")
        artworkFlip = defaults.bool(forKey: "artworkFlip")
        siteIcons = defaults.bool(forKey: "siteIcons")
        hideWhileSourceActive = defaults.bool(forKey: "hideWhileSourceActive")
        hideTitleExtras = defaults.bool(forKey: "hideTitleExtras")
        actionShuffle = defaults.bool(forKey: "actionShuffle")
        actionRepeat = defaults.bool(forKey: "actionRepeat")
        actionCopy = defaults.bool(forKey: "actionCopy")
        calendarEnabled = defaults.bool(forKey: "calendarEnabled")
        calendarReminderMinutes = defaults.integer(forKey: "calendarReminderMinutes")
        calendarSound = defaults.bool(forKey: "calendarSound")
        hourlyChime = defaults.bool(forKey: "hourlyChime")
        calendarUseColor = defaults.bool(forKey: "calendarUseColor")
        calendarExcluded = defaults.stringArray(forKey: "calendarExcluded") ?? []
        shelfEnabled = defaults.bool(forKey: "shelfEnabled")
        lockSoundOnLock = defaults.bool(forKey: "lockSoundOnLock")
        lockSoundOnUnlock = defaults.bool(forKey: "lockSoundOnUnlock")
        downloadsActivity = defaults.bool(forKey: "downloadsActivity")
        capsLockActivity = defaults.bool(forKey: "capsLockActivity")
        hasCompletedOnboarding = defaults.bool(forKey: "hasCompletedOnboarding")
    }

    /// Clears every stored setting and reloads the defaults.
    /// Each property assignment posts `changedNotification`, so observers react as if the user changed the value.
    /// Launch at login is left as it is, because the system owns it.
    func resetToDefaults() {
        if let domain = Bundle.main.bundleIdentifier {
            defaults.removePersistentDomain(forName: domain)
        }
        defaults.register(defaults: Self.defaultValues)
        reload()
    }

    /// Reads every property from `UserDefaults` again. Same lines as `init`, but here `didSet` runs.
    private func reload() {
        hideInFullscreen = defaults.bool(forKey: "hideInFullscreen")
        hideFromScreenCapture = defaults.bool(forKey: "hideFromScreenCapture")
        simulatedNotch = defaults.bool(forKey: "simulatedNotch")
        displayTarget = defaults.string(forKey: "displayTarget") ?? "auto"
        notchHeightOffset = defaults.double(forKey: "notchHeightOffset")
        notchWidthOffset = defaults.double(forKey: "notchWidthOffset")
        contrastOutline = defaults.bool(forKey: "contrastOutline")
        progressiveBlur = defaults.bool(forKey: "progressiveBlur")
        hapticFeedback = defaults.bool(forKey: "hapticFeedback")
        expandOnHover = defaults.bool(forKey: "expandOnHover")
        hoverDelay = defaults.double(forKey: "hoverDelay")
        gesturesEnabled = defaults.bool(forKey: "gesturesEnabled")
        globalHotkey = defaults.bool(forKey: "globalHotkey")
        animationSpeed = defaults.string(forKey: "animationSpeed") ?? "fast"
        batteryEnabled = defaults.bool(forKey: "batteryEnabled")
        batteryDuration = defaults.double(forKey: "batteryDuration")
        batteryLowPowerMode = defaults.bool(forKey: "batteryLowPowerMode")
        batteryWarnLow = defaults.bool(forKey: "batteryWarnLow")
        batteryLowThreshold = defaults.integer(forKey: "batteryLowThreshold")
        batterySound = defaults.bool(forKey: "batterySound")
        batteryHideLabel = defaults.bool(forKey: "batteryHideLabel")
        batteryHidePercentage = defaults.bool(forKey: "batteryHidePercentage")
        connectivityEnabled = defaults.bool(forKey: "connectivityEnabled")
        connectivityDuration = defaults.double(forKey: "connectivityDuration")
        connectivityWarnLow = defaults.bool(forKey: "connectivityWarnLow")
        connectivityLowThreshold = defaults.integer(forKey: "connectivityLowThreshold")
        connectivitySound = defaults.bool(forKey: "connectivitySound")
        focusEnabled = defaults.bool(forKey: "focusEnabled")
        focusDuration = defaults.double(forKey: "focusDuration")
        focusSound = defaults.bool(forKey: "focusSound")
        focusHideLabel = defaults.bool(forKey: "focusHideLabel")
        displayHUDEnabled = defaults.bool(forKey: "displayHUDEnabled")
        displayHUDDuration = defaults.double(forKey: "displayHUDDuration")
        displayHUDStyle = defaults.string(forKey: "displayHUDStyle") ?? "glow"
        displayHUDPercentage = defaults.bool(forKey: "displayHUDPercentage")
        displayHUDHideLabel = defaults.bool(forKey: "displayHUDHideLabel")
        keyboardHUDEnabled = defaults.bool(forKey: "keyboardHUDEnabled")
        soundHUDEnabled = defaults.bool(forKey: "soundHUDEnabled")
        soundHUDDuration = defaults.double(forKey: "soundHUDDuration")
        soundHUDStyle = defaults.string(forKey: "soundHUDStyle") ?? "accent"
        soundHUDPercentage = defaults.bool(forKey: "soundHUDPercentage")
        soundHUDHideLabel = defaults.bool(forKey: "soundHUDHideLabel")
        soundHUDShowDevice = defaults.bool(forKey: "soundHUDShowDevice")
        replaceSystemHUD = defaults.bool(forKey: "replaceSystemHUD")
        nowPlayingEnabled = defaults.bool(forKey: "nowPlayingEnabled")
        nowPlayingIdleDuration = defaults.double(forKey: "nowPlayingIdleDuration")
        nowPlayingSneakPeek = defaults.bool(forKey: "nowPlayingSneakPeek")
        waveformStyle = defaults.string(forKey: "waveformStyle") ?? "colored"
        liveWaveform = defaults.bool(forKey: "liveWaveform")
        compactWaveform = defaults.bool(forKey: "compactWaveform")
        artworkFlip = defaults.bool(forKey: "artworkFlip")
        siteIcons = defaults.bool(forKey: "siteIcons")
        hideWhileSourceActive = defaults.bool(forKey: "hideWhileSourceActive")
        hideTitleExtras = defaults.bool(forKey: "hideTitleExtras")
        actionShuffle = defaults.bool(forKey: "actionShuffle")
        actionRepeat = defaults.bool(forKey: "actionRepeat")
        actionCopy = defaults.bool(forKey: "actionCopy")
        calendarEnabled = defaults.bool(forKey: "calendarEnabled")
        calendarReminderMinutes = defaults.integer(forKey: "calendarReminderMinutes")
        calendarSound = defaults.bool(forKey: "calendarSound")
        hourlyChime = defaults.bool(forKey: "hourlyChime")
        calendarUseColor = defaults.bool(forKey: "calendarUseColor")
        calendarExcluded = defaults.stringArray(forKey: "calendarExcluded") ?? []
        shelfEnabled = defaults.bool(forKey: "shelfEnabled")
        lockSoundOnLock = defaults.bool(forKey: "lockSoundOnLock")
        lockSoundOnUnlock = defaults.bool(forKey: "lockSoundOnUnlock")
        downloadsActivity = defaults.bool(forKey: "downloadsActivity")
        capsLockActivity = defaults.bool(forKey: "capsLockActivity")
        hasCompletedOnboarding = defaults.bool(forKey: "hasCompletedOnboarding")
    }

    private func store(_ value: Any, _ key: String) {
        defaults.set(value, forKey: key)
        NotificationCenter.default.post(name: Self.changedNotification, object: key)
    }
}
