#!/usr/bin/env python3
"""Regenerates Islet/Core/Preferences.swift from the table below.

Run: python3 scripts/gen-preferences.py
"""
import os

SETTINGS = [
    ("// MARK: General",),
    ("hideInFullscreen", "Bool", "true"),
    ("hideFromScreenCapture", "Bool", "false"),
    ("simulatedNotch", "Bool", "false"),
    ("displayTarget", "String", '"auto"'),
    ("notchHeightOffset", "Double", "1.0"),
    ("notchWidthOffset", "Double", "0.0"),
    ("contrastOutline", "Bool", "false"),
    ("progressiveBlur", "Bool", "true"),
    ("hapticFeedback", "Bool", "true"),
    ("expandOnHover", "Bool", "true"),
    ("hoverDelay", "Double", "0.12"),
    ("gesturesEnabled", "Bool", "true"),
    ("globalHotkey", "Bool", "true"),
    ("animationSpeed", "String", '"fast"'),
    ("// MARK: Battery",),
    ("batteryEnabled", "Bool", "true"),
    ("batteryDuration", "Double", "3.0"),
    ("batteryLowPowerMode", "Bool", "true"),
    ("batteryWarnLow", "Bool", "true"),
    ("batteryLowThreshold", "Int", "20"),
    ("batterySound", "Bool", "true"),
    ("batteryHideLabel", "Bool", "false"),
    ("batteryHidePercentage", "Bool", "false"),
    ("// MARK: Connectivity",),
    ("connectivityEnabled", "Bool", "true"),
    ("connectivityDuration", "Double", "3.0"),
    ("connectivityWarnLow", "Bool", "true"),
    ("connectivityLowThreshold", "Int", "20"),
    ("connectivitySound", "Bool", "false"),
    ("// MARK: Focus",),
    ("focusEnabled", "Bool", "true"),
    ("focusDuration", "Double", "3.0"),
    ("focusSound", "Bool", "false"),
    ("focusHideLabel", "Bool", "false"),
    ("// MARK: Display HUD",),
    ("displayHUDEnabled", "Bool", "true"),
    ("displayHUDDuration", "Double", "1.5"),
    ("displayHUDStyle", "String", '"glow"'),
    ("displayHUDPercentage", "Bool", "true"),
    ("displayHUDHideLabel", "Bool", "false"),
    ("keyboardHUDEnabled", "Bool", "true"),
    ("// MARK: Sound HUD",),
    ("soundHUDEnabled", "Bool", "true"),
    ("soundHUDDuration", "Double", "1.5"),
    ("soundHUDStyle", "String", '"accent"'),
    ("soundHUDPercentage", "Bool", "true"),
    ("soundHUDHideLabel", "Bool", "false"),
    ("soundHUDShowDevice", "Bool", "true"),
    ("replaceSystemHUD", "Bool", "false"),
    ("// MARK: Now Playing",),
    ("nowPlayingEnabled", "Bool", "true"),
    ("nowPlayingIdleDuration", "Double", "3.0"),
    ("nowPlayingSneakPeek", "Bool", "true"),
    ("waveformStyle", "String", '"colored"'),
    ("liveWaveform", "Bool", "false"),
    ("compactWaveform", "Bool", "true"),
    ("artworkFlip", "Bool", "true"),
    ("siteIcons", "Bool", "true"),
    ("hideWhileSourceActive", "Bool", "false"),
    ("hideTitleExtras", "Bool", "false"),
    ("actionShuffle", "Bool", "true"),
    ("actionRepeat", "Bool", "true"),
    ("actionCopy", "Bool", "true"),
    ("// MARK: Calendar",),
    ("calendarEnabled", "Bool", "true"),
    ("calendarReminderMinutes", "Int", "15"),
    ("calendarSound", "Bool", "true"),
    ("hourlyChime", "Bool", "false"),
    ("calendarUseColor", "Bool", "true"),
    ("calendarExcluded", "[String]", "[]"),
    ("// MARK: Shelf",),
    ("shelfEnabled", "Bool", "true"),
    ("// MARK: Lock screen",),
    ("lockSoundOnLock", "Bool", "false"),
    ("lockSoundOnUnlock", "Bool", "true"),
    ("// MARK: Extras",),
    ("downloadsActivity", "Bool", "true"),
    ("capsLockActivity", "Bool", "true"),
    ("hasCompletedOnboarding", "Bool", "false"),
]

READERS = {"Bool": "bool", "Double": "double", "Int": "integer"}


def main():
    props, defaults, inits = [], [], []
    for entry in SETTINGS:
        if len(entry) == 1:
            props.append("    " + entry[0])
            continue
        name, kind, default = entry
        props.append(f'    var {name}: {kind} {{ didSet {{ store({name}, "{name}") }} }}')
        defaults.append(f'            "{name}": {default},')
        if kind == "String":
            inits.append(f'        {name} = defaults.string(forKey: "{name}") ?? {default}')
        elif kind == "[String]":
            inits.append(f'        {name} = defaults.stringArray(forKey: "{name}") ?? {default}')
        else:
            inits.append(f'        {name} = defaults.{READERS[kind]}(forKey: "{name}")')
    nl = "\n"
    source = f'''import Foundation
import Observation
import ServiceManagement

// Generated by scripts/gen-preferences.py. Edit the table in that script, then run it.

/// User settings. Every property writes through to `UserDefaults` and posts `changedNotification`.
@MainActor
@Observable
final class Preferences {{
    static let shared = Preferences()
    static let changedNotification = Notification.Name("IsletPreferencesChanged")
    private let defaults = UserDefaults.standard

{nl.join(props)}

    /// Launch at login is owned by the system, not by UserDefaults.
    var launchAtLogin: Bool {{
        get {{ SMAppService.mainApp.status == .enabled }}
        set {{
            do {{
                if newValue {{ try SMAppService.mainApp.register() }} else {{ try SMAppService.mainApp.unregister() }}
            }} catch {{
                NSLog("Islet: launch at login failed: \\(error)")
            }}
        }}
    }}

    private init() {{
        defaults.register(defaults: [
{nl.join(defaults)}
        ])
{nl.join(inits)}
    }}

    private func store(_ value: Any, _ key: String) {{
        defaults.set(value, forKey: key)
        NotificationCenter.default.post(name: Self.changedNotification, object: key)
    }}
}}
'''
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "Islet", "Core", "Preferences.swift")
    with open(path, "w") as f:
        f.write(source)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
